#
#	StaffSpy config
#

# Prefix for this awesome plugin, you know :)
pluginPrefix: "&8[&aStaff&cSpy&8]&r "
#If your SQL is configured, set this to true
isConfigured: false
# Host where plugin will try to open connection
host: "host"
# Database port
port: 3306
# Database name
database: "db"
# Table for users
tableUsers: "SS_USERS"
# Table for times
tableTimes: "SS_TIMES"
# Username for Database
username: "user"
# Password for Database
password: "password"