#
#	StaffSpy config
#

# Prefix for this awesome plugin, you know :)
pluginPrefix: "&8[&aStaff&cSpy&8]&r "
# Host where plugin will try to open connection
host: "host"
# Database port
port: 3306
# Database name
database: "db"
# Table name
table: "StaffSpy"
# Username for Database
username: "user"
# Password for Database
password: "password"